version: '3.7'

services:
  api:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - $API_PORT:$API_PORT
    env_file:
      - .env