version: '3.7'

services:
  api:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - $API_PORT:$API_PORT
    env_file:
      - .env
  
  postgress:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$POSTGRESS_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
    - $POSTGRES_PORT:$POSTGRES_PORT

volumes:
  postgres_data: